# Generated by Django 5.2.16 on 2026-07-26 04:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(default="")),
                ("photo_url", models.TextField(blank=True, default="")),
                ("base_price", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("label", models.CharField(blank=True, default="", max_length=50)),
            ],
            options={
                "db_table": "product",
            },
        ),
        migrations.CreateModel(
            name="Topping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("extra_price", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "topping",
            },
        ),
    ]
