# Generated by Django 5.2.16 on 2026-07-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0002_restaurant_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="slug",
            field=models.SlugField(editable=False, max_length=32, unique=True),
        ),
    ]
