# Generated by Django 5.2.16 on 2026-07-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0003_change_slug_to_random_alphanumeric"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
