# Generated by Django 5.2.16 on 2026-07-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0004_add_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="banner_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="primary_color",
            field=models.CharField(blank=True, default="#000000", max_length=7),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="secondary_color",
            field=models.CharField(blank=True, default="#FFFFFF", max_length=7),
        ),
    ]
