# Generated by Django 5.2.16 on 2026-07-31 06:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_add_white_label_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingHour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'operating_hour',
                'ordering': ['weekday'],
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'weekday'), name='unique_restaurant_weekday')],
            },
        ),
    ]
