# Generated by Django 5.2.16 on 2026-07-26 04:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference_number", models.CharField(max_length=20, unique=True)),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[
                            ("delivery", "Delivery"),
                            ("pickup", "Pickup"),
                            ("dine_in", "Dine in"),
                        ],
                        max_length=30,
                    ),
                ),
                ("address_line", models.TextField(blank=True, default="")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("cash_denomination", models.IntegerField(blank=True, null=True)),
                ("subtotal", models.IntegerField(blank=True, null=True)),
                ("delivery_fee", models.IntegerField(blank=True, null=True)),
                ("total", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("confirmed", "Confirmed"),
                            ("in_preparation", "In preparation"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_description", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "order",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("unit_price", models.IntegerField()),
            ],
            options={
                "db_table": "order_item",
            },
        ),
        migrations.CreateModel(
            name="OrderItemTopping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("extra_price", models.IntegerField()),
            ],
            options={
                "db_table": "order_item_topping",
            },
        ),
    ]
