# Generated by Django 5.2.16 on 2026-07-26 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0002_initial"),
        ("orders", "0001_initial"),
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="orders",
                to="restaurants.paymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="orders",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="items",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="order_items",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="orderitemtopping",
            name="order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="toppings",
                to="orders.orderitem",
            ),
        ),
        migrations.AddField(
            model_name="orderitemtopping",
            name="topping",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="order_item_toppings",
                to="catalog.topping",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["restaurant", "created_at"], name="idx_order_restaurant_created"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="idx_order_status"),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("delivery_type__in", ["delivery", "pickup", "dine_in"])
                ),
                name="order_valid_delivery_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "received",
                            "confirmed",
                            "in_preparation",
                            "completed",
                            "cancelled",
                        ],
                    )
                ),
                name="order_valid_status",
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["order"], name="idx_order_item_order"),
        ),
        migrations.AddIndex(
            model_name="orderitemtopping",
            index=models.Index(
                fields=["order_item"], name="idx_order_item_topping_item"
            ),
        ),
    ]
